### ISSUE TITLE
Investigate and document installing with Vundle and other package managers

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/scvim#1]
I think that most people these days use Vundle to install packages.

https://github.com/VundleVim/Vundle.vim

Somebody should test if that works and if so then make the install directions first suggest doing that. 

(I'm not saying that @danstowell should do it !)

Thanks for separating this out dan !

**Comment by danstowell** [comment]
No problem. I may as well be clear: I'm not currently an scvim user and I don't plan to do any work at all on this repository. I just did the git wizardry to separate it out. Would be nice to see vimmers forking and improving this repos

**Comment by dvzrv** [comment]
@danstowell thanks. that was an excellent choice!

@crucialfelix I don't think focussing only on vundle would be a good idea. There are many plugin managers out there to use. [VAM ](https://github.com/MarcWeber/vim-addon-manager/) is another.

However... is this now completely being outsourced from packaged versions of SuperCollider?
It's still a submodule, no?

**Comment by crucialfelix** [comment]
True, I mean package managers in general. That's what I meant by "etc." Vundle being one example.

It will still be included in the 3.8 release. We might move to remove it for 3.9. 

Pull requests would be great if you can document a better install. The current one in the README looks really long and complicated.

**Comment by dvzrv** [comment]
@crucialfelix "move to remove it for 3.9" meaning what exactly? I think it would be a good idea to leave it in for unix systems as it is a nice, lightweight solution.

I did some improvements for the last version and will try to do some more now, as soon as I find the time to do so.
Having it as a separate project is a very good first step though! :)

**Comment by danstowell** [comment]
@dvzrv it remains as a nice lightweight solution - but the argument seems to be that it would fit more neatly into the vim ecosystem if people installed it using their vim package managers, rather than as a part of SuperCollider's own download and/or build system. That doesn't stop it from being available/used ;)

I would suggest that for 3.9 we can simply set the default build option SCVIM=0 so that people can still install it directly but by default we don't clash with the vim package management.

**Comment by dvzrv** [comment]
@danstowell okay. that sounds reasonable.
I'll look into fixing the README soon then, to incorporate some installation information for addon managers

**Comment by gusano** [comment]
`scvim` is now a vim plugin =)
