### ISSUE TITLE
execution visually represented?

### ISSUE THREAD

**Issue by K0F** [supercollider/scvim#12]
It is not an issue, it rather suggestion or question:

I use ScVim quite often now even for live-coding performances, I was wondering if there is a chance to get the blocks of code highlighted while being executed (as in ScIde for instance)?

Maybe more Vim question…

whatever, any ideas or suggestions?

thx!

**Comment by blacksound** [comment]
Thanks @K0F for raising this issue. Closing it now since @gusano is addressing this in #21.

**Comment by brianlheim** [comment]
(side note: issues are usually closed after the PR addressing them is merged.)

**Comment by blacksound** [comment]
Auwww! I wasn't aware of that, sorry for the noise.
