### ISSUE TITLE
Character literals are not interpreted

### ISSUE THREAD

**Issue by gusano** [supercollider/scvim#24]
Character literals are not escaped and therefore not passed to sc interpreter:

```javascript
x = $a

// -> nil

x = [ $1, $a ]

// ERROR: syntax error, unexpected ',', expecting ']'
//   x = [ ,  ]
//         ^
```

Also kinda related: https://github.com/supercollider/supercollider/issues/2660

**Comment by dvzrv** [comment]
Related: https://github.com/supercollider/supercollider/issues/2887
