### ISSUE TITLE
Zombie commands in Arch Linux?

### ISSUE THREAD

**Issue by kflak** [supercollider/scvim#35]
I am experiencing a strange issue that I can't quite pin down the reason for: When I work in scvim I keep getting disturbed by the message "Press ENTER or type command to continue". This is exclusive to scvim, ie. it doesn't happen when I work in vim elsewhere. I am running this on the latest Arch kernel, sc3.9dev, I have the latest version of scvim (at least I have been running PluginUpdate, so it should be OK...). scvim is running without any extraneous options, the only mention of it is let g:sclangTerm = "xfce4-terminal -x $SHELL -ic" in .vimrc.
My full .vimrc is here: https://pastebin.com/V5sQHat5
I have been running basically the same setup on macOS without a hitch, this is brand new to me... (oh, and I am a complete Linux rookie, so please bear with me if this is something so, so basic...)

**Comment by gusano** [comment]
@kflak never saw that one but from a quick search in google I found [that](http://vim.wikia.com/wiki/Avoiding_the_%22Hit_ENTER_to_continue%22_prompts).
Not sure what causes this though, running latest Archlinux and scvim and I don't see that.

I'd suggest you disable all your vim plugins and only keep scvim with the most basic `.vimrc` possible to narrow it down.

**Comment by kflak** [comment]
OK, I 've been able to narrow it down to a specific project. It doesn't happen when I run a bare-bones test .scd with only a SinOsc. The project where it happens is getting awfully complex with a lot of ins and outs, so I suspect this is where the canine is buried. Will test further!
