### ISSUE TITLE
Running block of code between parenthesis sometimes doesn't work

### ISSUE THREAD

**Issue by ghost** [supercollider/scvim#42]
So, if I press F5 inside a code block (between "()") sometimes it returns an error:

`
Error detected while processing function SClang_block[1]..findOuterMostBlock:
`

**Comment by devdevnullnull** [comment]
Following on this, its difficult to trace the bug, since it doesn't behave consistently. For example, having to identical block, one works, the other one doesn't. 
I'm don't really know vimscript, and fixing a bug in a parser like de FindOuterMostBlock function is not an easy task

**Comment by capocasa** [comment]
Please give an example of a block that doesn't work, @ghost. They might differ by whitespace.
Thanks!

**Comment by brianlheim** [comment]
@ghost is the username GitHub uses for a deleted user. Since no more info will be provided, I'm closing this.
