### ISSUE TITLE
executing a visually selected block doesn't work

### ISSUE THREAD

**Issue by grirgz** [supercollider/scvim#43]
I recently updated from an old version of supercollider and configured this new scvim. But i can't anymore execute a block of code which i selected in visual mode. It seems that's instead it just run "execute one line" on each line of the block

this works:

1.postln;
2.postln;

give me the result:

1
-> 1
2
-> 2

this doesn't work:

3.do { arg x;
    x.postln;
}

give me the result:

ERROR: syntax error, unexpected $end, expecting '}'
  in interpreted text
  line 2 char 1:

   
   
-----------------------------------
ERROR: Command line parse failed
-> nil
nil
-> nil
ERROR: Parse error
  in interpreted text
  line 1 char 1:

  }
  ^
   
-----------------------------------
unmatched '}'
  in interpreted text line 1 char 1
ERROR: syntax error, unexpected BADTOKEN, expecting $end
  in interpreted text
  line 1 char 1:

  }
  ^
   
-----------------------------------
ERROR: Command line parse failed
-> nil

**Comment by grirgz** [comment]
I didn't do a bisect but i checked the first version of the file and it was a lot easier to fix than I thought! =)
see pull request #44

**Comment by dvzrv** [comment]
closed with #44
