### ISSUE TITLE
Completer for youcompleteme

### ISSUE THREAD

**Issue by dvzrv** [supercollider/scvim#5]
It would be most awesome to write a completer for [youcompleteme](https://github.com/Valloric/YouCompleteMe).
The ycm plugin is the overall approach for completion and preview for vim and people are even [thinking about merging it into neovim](https://github.com/neovim/neovim/issues/396).

I'd like to see ycm be able to handle SuperCollider. I think this would be a very good improvement.

**Comment by crucialfelix** [comment]
atom-supercollider would also like to provide suggestions to the various completers available there. currently I use ctags or atom can generate symbols using the syntax definition.

a simple ctags definition is here: https://gist.github.com/crucialfelix/74e5bfe0535e077cd1bf

and you can read that into ycm: https://github.com/Valloric/YouCompleteMe#the-gycm_collect_identifiers_from_tags_files-option

better would be to have a utility that exports the current library as symbols in a json file that can then be translated or used by providers on various platforms.

**Comment by dvzrv** [comment]
@crucialfelix I was actually aiming at this: https://github.com/Valloric/ycmd/blob/master/ycmd/completers/completer.py

Thanks for the ctags hints though!
As for the export, we still have the old way of exporting the library, but it can't be reused too nicely.

I've experimented with directly accessing the schelp files with scvim and that works quite nicely too.
Mostly you can just evaluate code and so on, but this approach obviously lacks the nice pictures and so on :)

**Comment by crucialfelix** [comment]
what is the old way you exported it ? can you point me at some code for reference ?

I'm thinking just a JSON dump. completer.py subclass can read it easily

**Comment by dvzrv** [comment]
That would be helpful then!

The "object caches" are created [here](https://github.com/supercollider/scvim/blob/master/scclasses/SCVim.sc#L48) and used [like this](https://github.com/supercollider/scvim/blob/master/ftplugin/supercollider.vim#L418) in scvim

[UpdateHelp](https://github.com/supercollider/scvim/blob/master/scclasses/SCVim.sc#L98
) could be dumped then as well and help be accessed in schelp files, maybe?
Would be cool to have an all integrated vim solution. It would obviously lack displaying pictures.
Nonetheless from what I've realized is, that the help files are not being properly generated (for HelpBrowser), when using scvim. Using SCIDE it's just fine.
I guess this is another issue though :)

**Comment by capocasa** [comment]
Apparently abandoned
