### ISSUE TITLE
scvim dose not load $SCVIM_TAGFILE

### ISSUE THREAD

**Issue by yuanyelele** [supercollider/scvim#50]
Please add "" around the environment variable in plugin/supercollider.vim:
`if exists("$SCVIM_TAGFILE")`
otherwise, on my system, vim cannot add it to tagfiles.

see:
https://github.com/vim/vim/blob/d6105cb4085ad166910897a640693d3bada603e1/runtime/doc/eval.txt#L3741

**Comment by capocasa** [comment]
Reproduced the problem

**Comment by capocasa** [comment]
Created the PR #61 , please review and merge

**Comment by brianlheim** [comment]
@capocasa typically we only close issues when the corresponding PR has been merged
