### ISSUE TITLE
supercollider with vim

### ISSUE THREAD

**Issue by ovitus** [supercollider/scvim#51]
I installed the following Supercollider rpms through the PlanetCCRMA repository: 
supercollider-3.9.3-1.fc29.ccrma.x86_64.rpm
supercollider-vim-3.9.3-1.fc29.ccrma.x86_64.rpm

When I open a test.sc with vim, and try :SClangStart I get:
E492: Not an editor command: SClangStart

Is there something I'm missing?

**Comment by gusano** [comment]
I am not sure how Fedora installs vim plugins but, [as stated in `scvim` README.md](https://github.com/supercollider/scvim#scvim-plugin-installation):

> It is highly recommended to use a plugin manager to install `scvim`

You should try that

**Comment by gusano** [comment]
Closing as this is a RPM package issue, unrelated to this repo
