### ISSUE TITLE
installation help

### ISSUE THREAD

**Issue by ovitus** [supercollider/scvim#52]
I've been trying to follow the readme.

I setup pathogen and installed scvim into ~/.vim/bundle

I created ~/.vimrc with the following:
execute pathogen#infect()
let g:sclangTerm = "x-terminal-emulator -e $SHELL -ic"
syntax on
filetype plugin indent on

I created a system link:
ln -s ~/.vim/bundle/scvim/sc/SCVim.sc ~/.local/share/SuperCollider/Extensions

Then I test it:
vim test.sc
:SClangStart

s.boot;
(
  Pbind(
    \freq, Pn(Pseries(110, 111, 10), 2),
    \dur, 1/2,
    \legato, Pwhite(0.1, 1)
  ).play;
    Pbind(
    \freq, Pn(Pseries(220, 222, 10), 4),
    \dur, 1/4,
    \legato, Pwhite(0.1, 1)
  ).play;
  Pbind(
    \freq, Pn(Pseries(330, 333, 10), 6),
    \dur, 1/6,
    \legato, 0.1
  ).play;
)

F6 to evaluate s.boot; and F5 to evaluate the block. I see :call SClang_block(), but I hear nothing.

Shouldn't I be seeing a Post or Help window in vim after executing :SClangStart?

I guess I could have put the link in /usr/share/SuperCollider/Extensions. IDK if that makes a difference. I get E492: Not an editor command: SClangStart when trying to run :SClangStart as root.

**Comment by gusano** [comment]
I don't use `pathogen` so I cannot really tell if you installed `scvim` properly (I use https://github.com/junegunn/vim-plug which is very minimal and fast).

Where is SuperCollider installed?
Your symlink needs to go in your Extensions folder, not into a guessed one..
Check it out with `Platform.systemExtensionDir`

What happens if you open any `*.scd` file and run `:SClangStart`? Can you evaluate `"hello".postln` with F6?

**Comment by ovitus** [comment]
Platform.systemExtensionDir tells me the directory is /usr/share/SuperCollider/Extensions. I created a symlink there:
lrwxrwxrwx. 1 root root 43 Nov 15 14:48 SCVim.sc -> /home/user/.vim/bundle/scvim/sc/SCVim.sc

When I open test.scd and run :SClangStart and F6 on "hello".postln I get :call SClang_block(). Still I don't see any Post window, just looks like regular vim. Am I supposed to after running :SClangStart?

I will try vim-plug as well.

**Comment by ovitus** [comment]
![vim-plug](https://user-images.githubusercontent.com/44982087/48636115-f7b57d00-e997-11e8-9e9f-f3ea1ef54505.png)

I installed scvim via vim-plug, but I'm still getting nothing.
