### ISSUE TITLE
Disable gpu

### ISSUE THREAD

**Issue by kflak** [supercollider/scvim#53]
Please check [this](https://github.com/supercollider/supercollider/issues/4201) issue over at the main supercollider repo. Short recap: the help browser is crashing on me, both using wayland and xorg with nouveau drivers. It seems to be caused by a known qtwebengine/noveau issue, and is solved in scide by running with scide --disable-gpu. I would like to disable gpu in scvim as well, but don't know where to start! Most of all, though, I would like to get rid of the help browser as such, and rather have access to the help files natively in vim! At the moment I am using w3m on a local copy of doc.sccode.org, but this is pretty far from an ideal workflow...

System: Arch Linux 4.14.71-rt44-1-rt-lts/swaywm/urxvt/scvim/sclang 3.10.0

**Comment by kflak** [comment]
Normal use of scvim works fine, the only issue I have is with the help browser, which crashes and (sometimes) brings sclang with it.

**Comment by dvzrv** [comment]
@kflak seeing that you're on Arch and presumably currently on qt5 5.11.2: [qt5 5.12 is already in testing](https://www.archlinux.org/packages/?sort=&repo=Testing&q=qt5&maintainer=&flagged=). This might fix things for you. Please do report back, once 5.12.0 is available!

That being said: I'm all up for the no-help-browser solution (even by default)!
AFAIK, there are [these functions](https://www.archlinux.org/packages/?sort=&repo=Testing&q=qt5&maintainer=&flagged=) being [called from here](https://github.com/supercollider/scvim/blob/master/plugin/supercollider.vim#L46). That is a call to sclang though, so not sure how well that translates to the flag for scide.

**Comment by kflak** [comment]
Cool, I am stil not brave enough to dip my toes into testing, but I will check how things work out once the update hits the official repos! And when I have a moment, I'll take a look at the scvim help func. Maybe I can simply redirect the request to a browser...

**Comment by kflak** [comment]
No joy with 5.12.0, unfortunately. Help browser is crashing on me still, but not in a consistent way. Mosty it just dies immediately with something like this:
```
QObject::connect: No such slot QtCollider::WebView::onRenderProcessTerminated(RenderProcessTerminationStatus, int)
JavaScript Message: WebSocket connection to 'ws://localhost:12344/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
JavaScript Message: WebChannel error: [object Event]
Received signal 11 SEGV_MAPERR 000000000008
#0 0x7f9d237f298e <unknown>
#1 0x7f9d237eb713 <unknown>
#2 0x7f9d237f2905 <unknown>
#3 0x7f9d2a18f3c0 <unknown>
#4 0x7f9d10c2edbe <unknown>
#5 0x7f9d10c2fa19 <unknown>
#6 0x7f9d1101799e <unknown>
#7 0x7f9d11017a97 <unknown>
#8 0x7f9d110190c8 <unknown>
#9 0x7f9d11214f20 <unknown>
#10 0x7f9d112ad369 <unknown>
#11 0x7f9d112ae18c <unknown>
#12 0x7f9d2110ee1b QSGBatchRenderer::Renderer::renderMergedBatch()
#13 0x7f9d2110fe06 QSGBatchRenderer::Renderer::renderBatches()
#14 0x7f9d21115653 QSGBatchRenderer::Renderer::render()
#15 0x7f9d21105a3e QSGRenderer::renderScene()
#16 0x7f9d21105ee0 QSGRenderer::renderScene()
#17 0x7f9d211431a0 QSGDefaultRenderContext::renderNextFrame()
#18 0x7f9d211a7085 QQuickWindowPrivate::renderSceneGraph()
#19 0x7f9d2127044a QQuickRenderControl::render()
#20 0x7f9d20f89407 <unknown>
#21 0x7f9d20f895d7 <unknown>
#22 0x7f9d2900cb1b QObject::event()
#23 0x7f9d299eae8c QWidget::event()
#24 0x7f9d20f8d29e QQuickWidget::event()
#25 0x7f9d2a16b291 <unknown>
#26 0x7f9d299a9e34 QApplicationPrivate::notify_helper()
#27 0x7f9d299b1671 QApplication::notify()
#28 0x7f9d28fe18f9 QCoreApplication::notifyInternal2()
#29 0x7f9d29036955 QTimerInfoList::activateTimers()
#30 0x7f9d290371e2 <unknown>
#31 0x7f9d201c93cf g_main_context_dispatch
#32 0x7f9d201caf89 <unknown>
#33 0x7f9d201cafce g_main_context_iteration
#34 0x7f9d290375a9 QEventDispatcherGlib::processEvents()
#35 0x7f9d28fe058c QEventLoop::exec()
#36 0x7f9d28fe8896 QCoreApplication::exec()
#37 0x55fc8745c8fa <unknown>
#38 0x55fc8744ef92 <unknown>
#39 0x55fc8743e08c <unknown>
#40 0x7f9d28027223 __libc_start_main
#41 0x55fc8744c5ce <unknown>
  r8: 0000000000000053  r9: 0000000000000098 r10: 000055fc881f7370 r11: 000055fc881f6430
 r12: 000055fc881f6e80 r13: 0000000000000000 r14: 0000000000000000 r15: 0000000000000000
  di: 000055fc881f7140  si: 0000000000000000  bp: 0000000000000000  bx: 0000000000000000
  dx: 0000000000000000  ax: 0000000000000004  cx: 000055fc881f7140  sp: 00007ffc053409d0
  ip: 00007f9d10c2edbe efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000008
[end of stack trace]
Calling _exit(1). Core file will not be generated.

```

... or it lets me play around a little bit before locking up completely and corrupting the graphics of the screen.

**Comment by b1tfl0w** [comment]
Same problem here but with an Intel card Ironlake Mobile, so no gpu..If I start Supercollider everything is fine
```
*** Welcome to SuperCollider 3.10.0. *** For help type :SChelp.
qt5ct: palette support is disabled
finished generating tagsfile
-> SCVim
SCDoc: Indexing help-files...
SCDoc: Indexed 1911 documents in 9.14 seconds
QObject::connect: No such slot QtCollider::WebView::onRenderProcessTerminated(RenderProcessTerminationStatus, int)
```
My system: Ubuntu 18.04
SuperCollider 3.10
compiled from git source

**Comment by gusano** [comment]
@kflak This issue is not about HelpBrowser crashing in `scvim` but about disabling HelpBrowser so I'm gonna rename it to not have the same issue twice.

**Comment by kflak** [comment]
@gusano Cool!

**Comment by capocasa** [comment]
> have access to the help files natively in vim

That would be cool.

Closest I can come is to do `grep mySearch` /usr/share/SuperCollider/HelpSource and then manually open the results.

> disable gpu in scvim as well

Actually, scvim doesn't use the help browser at all- it just sends the command HelpBrowser.openHelpFor("something") to the sclang client. Hate to pass a the buck, but I'm gonna pass the buck- the gpu needs to be disabled within sclang, because that's where the Qt window is coming from. I was digging a little on how to do that, but couldn't find anything reasonably quickly. If you figure it out, and scvim needs to change to accomodate your solution, please open another issue  (or a pull request for extra karma)

Thanks for reporting!!!
