### ISSUE TITLE
Errors on Ubuntu 19.04

### ISSUE THREAD

**Issue by jeromecovington** [supercollider/scvim#57]
Hello, I'm really hoping to get scvim working on my Ubuntu 19.04 install. When I enter `SCLandStart` the server window opens, but this is the output:
```shell
	Compiling directory '/usr/share/SuperCollider/SCClassLibrary'
	Compiling directory '/usr/share/SuperCollider/Extensions'
	Compiling directory '/home/jcovingt/.local/share/SuperCollider/Extensions'
	numentries = 818594 / 11958602 = 0.068
	5353 method selectors, 2234 classes
	method table size 13112760 bytes, big table size 95668816
	Number of Symbols 12127
	Byte Code Size 364116
	compiled 317 files in 0.46 seconds

Info: 4 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Couldn't set realtime scheduling priority 1: Operation not permitted
Class tree inited in 0.01 seconds


*** Welcome to SuperCollider 3.10.0. *** For help type :SChelp.
Couldn't set realtime scheduling priority 1: Operation not permitted
```

...And unfortunately any lines I try to evaluate and play don't have any effect that I can tell (silence). Any one else experiencing this issue or similar issues?

**Comment by brianlheim** [comment]
thanks for reporting! this is likely not related to scvim; please ask on the mailing list or Slack for help with this. i recall other users running into the same problem, but since I'm not on Ubuntu i haven't paid much attention to that and can't be of much assistance myself.
