### ISSUE TITLE
Make scvim true filetype plugin

### ISSUE THREAD

**Issue by dvzrv** [supercollider/scvim#6]
I'd like to make scvim a true filetype based plugin.
Currently it's started through using the scvim script, but that's not needed at all. vim can decide upon filetype and just use the plugin.
Maybe I'm wrong here and there was some abstract use-case for it (once)?

In any case I've tested this, but have unfortunately overwritten my local changes by testing an alpha of 3.7 back in the day.
Will reconstruct and do a pull request.

**Comment by blacksound** [comment]
I do like the way it feels in scel actually. You can edit sc/scd files in the SCLang mode, and startup the interpreter if needed.
Maybe this also points in the direction of replacing the ruby pipe with a bash?

**Comment by dvzrv** [comment]
Well, having it properly integrated makes much sense actually. All other filetype based plugins work that way. Using a wrapper script to start vim with predefined parameters actually feels more like a dirty hack. ;)
I thought this is also one of the reasons why scvim was placed in a separate repository?
scvim is a vim addon, not a wrapper. sclang is enough of a separate piece of software to be run/ worked with from a plugin, that is started/used when vim encounters .scd, .sc or .schelp files.

Right now it's only possible to work on the files in vim (when not run through scvim executable), but the filetype stuff doesn't work properly (as in, no syntax highlighting, etc.). Also, it's not possible to start the interpreter when just running vim.

And: This is not about making the pipe run in a different way (yet). It's only about vim properly recognizing, that it should run the plugin based on file extension, instead of wrapping vim in a script that is static.
This way people will have the highest possible configuration possibility on their side.

If you feel that it should behave more like scel, we can maybe make the autostart of the pipe configurable?

In any case, working on this will lead to more configurability :)

**Comment by carlocapocasa** [comment]
I use this in my .vimrc, but I am unsure at this point what the correct way is to include it directly in the plugin to provide a clean update avoiding issues like mapping conflicts.

I chose F9 to start the terminal, but it could be replaced with something more commonly used that I wasn't aware of.

```
" Supercollider Settings
au Filetype supercollider nmap <F3> :call SCfindArgs()<CR>
au Filetype supercollider nmap <buffer> <F2> :call SClangRecompile()<CR>
au Filetype supercollider imap <buffer> <F2> call SClangRecompile()<CR>a
au Filetype supercollider vmap <buffer> <F2> :call SClangRecompile()<CR>
au Filetype supercollider nmap <buffer> <F9> :call SClangStart()<CR>
au Filetype supercollider imap <buffer> <F9> call SClangStart()<CR>a
au Filetype supercollider vmap <buffer> <F9> :call SClangStart()<CR>
au Filetype supercollider nmap <buffer> <F10> :call SClangKill()<CR>
au Filetype supercollider imap <buffer> <F10> call SClangKill()<CR>a
au Filetype supercollider vmap <buffer> <F10> :call SClangKill()<CR>

au Filetype supercollider imap <buffer> <F5> <ESC><F5>i
au Filetype supercollider imap <buffer> <F6> <ESC><F6>i

```

**Comment by dvzrv** [comment]
Related pull request #40.

**Comment by capocasa** [comment]
I'd love to see this, but it would appear to have been abandoned.
