### ISSUE TITLE
need help installing

### ISSUE THREAD

**Issue by grammoboy2** [supercollider/scvim#66]
sorry, but can't get it working on debian testing. I'm new to vim...

Installed scvim via vim-plug
Added the symlink

But when I start :SClangStart it gives me a flashing terminal, but it doesn't launch.

edit: Did try to add
let g:sclangTerm = "gnome-terminal -x $SHELL -ic"

to .vimrc, but doesn't change anything (just put it somewhere in the file?)

Installed gnome-terminal, but would prefer lxterminal

**Comment by brianlheim** [comment]
hey @grammoboy2 ! thanks for the report. issues with installation and configuration are best direct to the [sc-users](https://www.birmingham.ac.uk/facilities/ea-studios/research/supercollider/mailinglist.aspx) mailing list or [scsynth.org](https://scsynth.org/). those places are much more active and you're more likely to get a helpful answer quickly.

**Comment by colin-axner** [comment]
hello @grammoboy2 :wave: Did you happen to solve this issue? I'm running into the same issue you describe above

**Comment by grammoboy2** [comment]
I think I did. Maybe you can find it in the archives of the sc-user mailinglist around the date of the issue. I'm now using scnvim, so can't help you much I'm afraid. But let's say, there is hope ;)
