### ISSUE TITLE
[0108/181607.596102:WARNING:stack_trace_posix.cc(699)] Failed to open file: /memfd:/.glXXXXXX (deleted)

### ISSUE THREAD

**Issue by ovitus** [supercollider/scvim#71]
Any idea what this error is about? I always see it when starting scvim:

```
/home/awright/.vim/plugged/scvim/bin/start_pipe
awright@ovitus:~/tidal$ /home/awright/.vim/plugged/scvim/bin/start_pipe
compiling class library...
[0108/181607.596102:WARNING:stack_trace_posix.cc(699)] Failed to open file: /memfd:/.glXXXXXX (deleted)
Error: No such file or directory
Found 845 primitives.
Compiling directory '/usr/share/SuperCollider/SCClassLibrary'
Compiling directory '/usr/share/SuperCollider/Extensions'
Compiling directory '/home/awright/.local/share/SuperCollider/Extensions'
Compiling directory '/home/awright/.local/share/SuperCollider/downloaded-quarks/Vowel'
Compiling directory '/home/awright/.local/share/SuperCollider/downloaded-quarks/Dirt-Samples'
Compiling directory '/home/awright/.local/share/SuperCollider/downloaded-quarks/SuperDirt'      
numentries = 1189267 / 18280590 = 0.065                                                         
5745 method selectors, 3182 classes
method table size 19375088 bytes, big table size 146244720
Number of Symbols 14482
Byte Code Size 415003
compiled 457 files in 0.68 seconds
```

**Comment by dvzrv** [comment]
@ovitus that looks like an issue with sclang, not scvim.

Could you elaborate how you install supercollider and scvim and on which operating system you are on?
Also, do you see this when just calling `sclang` (you can quit it with e.g. ctrl+d again) in a terminal?

**Comment by ovitus** [comment]
I'm on Debian 10 (buster) and have SuperCollider version 3.10.0 installed via the stock repository. I see it when calling sclang also.

**Comment by dvzrv** [comment]
I believe that this is an issue with either sclang in general or sclang in that version on Debian in particular (I can not reproduce this on Arch Linux with supercollider 3.11.2). Maybe there is a chance to get a more recent version of supercollider for you.

That said: You can either file a ticket against the supercollider project or (probably better, given the dated supercollider version) against your distribution.
